import type { PlanetParameters } from './planetParams.js';

// Relief amplitudes (voronoi/detail/texture/polar) are ratios of radius
// (scale-independent); the shader multiplies them by radius. Presets were
// authored at radius 100, so their old absolute metres ÷ 100 give the ratios —
// identical shape at radius 100, proportional at any other size.
export const PLANET_PRESETS = {
	starter: {
		radius: 100,
		voronoi_scale: 1,
		voronoi_amplitude: 0.01,
		voronoi_albedo: 1,
		voronoi_albedo_y: 1,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 0,
		voronoi_distortion_amplitude: 0,
		voronoi_distortion_albedo: 1,
		detail_scale: 0,
		detail_amplitude: 0,
		detail_albedo: 1,
		water_level: 0.4,
		render_water: 1.0,
		erosion: 1,
		sand_cutoff: 0,
		vegetation_level: 0,
		snow_cover: 1,
		texture_noise_scale: 0,
		texture_noise_amplitude: 0,
		polar_scale: 0,
		polar_amplitude: 0,
		illumination: 1.0
	},
	twirly: {
		radius: 100,
		voronoi_scale: 1,
		voronoi_amplitude: 0.12,
		voronoi_albedo: 0.23,
		voronoi_albedo_y: 0.91,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 0.3,
		voronoi_distortion_amplitude: 46.8,
		voronoi_distortion_albedo: 1,
		detail_scale: 8,
		detail_amplitude: 0.05,
		detail_albedo: 0.93,
		water_level: 0.46,
		render_water: 1.0,
		erosion: 1,
		sand_cutoff: 0.07,
		vegetation_level: 0.25,
		snow_cover: 0.42,
		texture_noise_scale: 0.29,
		texture_noise_amplitude: 0.0173,
		polar_scale: 0,
		polar_amplitude: 0,
		illumination: 1.0
	},
	desert: {
		radius: 100,
		voronoi_scale: 1,
		voronoi_amplitude: 0.091,
		voronoi_albedo: 0.66,
		voronoi_albedo_y: 0.91,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 1.9,
		voronoi_distortion_amplitude: 7,
		voronoi_distortion_albedo: 1,
		detail_scale: 1.2,
		detail_amplitude: 0.235,
		detail_albedo: 0.93,
		water_level: 0.37,
		render_water: 1.0,
		erosion: 1.59,
		sand_cutoff: 0.04,
		vegetation_level: 0,
		snow_cover: 0.18,
		texture_noise_scale: 0.04,
		texture_noise_amplitude: 0.0402,
		polar_scale: 0.15,
		polar_amplitude: 0.023,
		illumination: 1.0
	},
	archipelago: {
		radius: 100,
		voronoi_scale: 8,
		voronoi_amplitude: 0.091,
		voronoi_albedo: 0.66,
		voronoi_albedo_y: 0.91,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 1.3,
		voronoi_distortion_amplitude: 6.5,
		voronoi_distortion_albedo: 1,
		detail_scale: 31.7,
		detail_amplitude: 0.032,
		detail_albedo: 0.96,
		water_level: 0.66,
		render_water: 1.0,
		erosion: 1.03,
		sand_cutoff: 0.44,
		vegetation_level: 0.54,
		snow_cover: 0.61,
		texture_noise_scale: 0.04,
		texture_noise_amplitude: 0.0377,
		polar_scale: 0.28,
		polar_amplitude: 0.006,
		illumination: 1.0
	},
	frozen: {
		radius: 100,
		voronoi_scale: 8,
		voronoi_amplitude: 0.019,
		voronoi_albedo: 0.78,
		voronoi_albedo_y: 0.91,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 10,
		voronoi_distortion_amplitude: 6.5,
		voronoi_distortion_albedo: 0.78,
		detail_scale: 31.7,
		detail_amplitude: 0.032,
		detail_albedo: 0.19,
		water_level: 0.35,
		render_water: 1.0,
		erosion: 1.03,
		sand_cutoff: 0.3,
		vegetation_level: 0.36,
		snow_cover: 0.46,
		texture_noise_scale: 0.04,
		texture_noise_amplitude: 0.0377,
		polar_scale: 0,
		polar_amplitude: 0.186,
		illumination: 1.0
	},
	craters: {
		radius: 100,
		voronoi_scale: 2.6,
		voronoi_amplitude: 0.116,
		voronoi_albedo: 1,
		voronoi_albedo_y: 1,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 0.5,
		voronoi_distortion_amplitude: 2.3,
		voronoi_distortion_albedo: 1,
		detail_scale: 7.2,
		detail_amplitude: 0.015,
		detail_albedo: 0.55,
		water_level: 0.41,
		render_water: 1.0,
		erosion: 0.44,
		sand_cutoff: 0.35,
		vegetation_level: 0.47,
		snow_cover: 0.82,
		texture_noise_scale: 1.56,
		texture_noise_amplitude: 0.0173,
		polar_scale: 0,
		polar_amplitude: 0,
		illumination: 1.0
	},
	normie: {
		radius: 100,
		voronoi_scale: 1,
		voronoi_amplitude: 0.256,
		voronoi_albedo: 0.85,
		voronoi_albedo_y: 1,
		voronoi_albedo_z: 1,
		voronoi_distortion_scale: 2,
		voronoi_distortion_amplitude: 4,
		voronoi_distortion_albedo: 1,
		detail_scale: 47.8,
		detail_amplitude: 0.082,
		detail_albedo: 0.55,
		water_level: 0.5,
		render_water: 1.0,
		erosion: 1.61,
		sand_cutoff: 0.17,
		vegetation_level: 0.27,
		snow_cover: 0.39,
		texture_noise_scale: 0.46,
		texture_noise_amplitude: 0.025,
		polar_scale: 0.15,
		polar_amplitude: 0.121,
		illumination: 1.0
	}
} as const satisfies Record<string, PlanetParameters>;

export type PlanetPresetName = keyof typeof PLANET_PRESETS;

export const DEFAULT_PRESET: PlanetPresetName = 'normie';
